version: 1.2
workflows:
   - name: cnv_germline_case_scattered_workflow
     subclass: WDL
     primaryDescriptorPath: /scripts/cnv_wdl/germline/cnv_germline_case_scattered_workflow.wdl
     testParameterFiles:
          - /scripts/cnv_cromwell_tests/germline/cnv_germline_case_scattered_workflow.json
     filters:
         branches: 
             - master
         tags:
             - /.*/
   - name: cnv_germline_case_workflow
     subclass: WDL
     primaryDescriptorPath: /scripts/cnv_wdl/germline/cnv_germline_case_workflow.wdl
     testParameterFiles:
          -  /scripts/cnv_cromwell_tests/germline/cnv_germline_case_scattered_workflow.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: cnv_germline_cohort_workflow
     subclass: WDL
     primaryDescriptorPath: /scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl
     testParameterFiles:
          -  /scripts/cnv_cromwell_tests/germline/cnv_germline_cohort_workflow.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: cnv_somatic_pair_workflow
     subclass: WDL
     primaryDescriptorPath: /scripts/cnv_wdl/somatic/cnv_somatic_pair_workflow.wdl
     testParameterFiles: 
          -  /scripts/cnv_cromwell_tests/somatic/cnv_somatic_pair_wes_do-gc_workflow.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: cnv_somatic_panel_workflow
     subclass: WDL
     primaryDescriptorPath: /scripts/cnv_wdl/somatic/cnv_somatic_panel_workflow.wdl
     testParameterFiles:
          -  /scripts/cnv_cromwell_tests/somatic/cnv_somatic_panel_wes_do-gc_workflow.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: cnv_joint_call_exomes
     subclass: WDL
     primaryDescriptorPath: /scripts/cnv_wdl/germline/joint_call_exome_cnvs.wdl
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: cram2filtered
     subclass: WDL
     primaryDescriptorPath: /scripts/cnn_variant_wdl/cram2filtered.wdl
     testParameterFiles:
          - /scripts/cnn_variant_wdl/jsons/cram2filtered.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: cram2model
     subclass: WDL
     primaryDescriptorPath: /scripts/cnn_variant_wdl/cram2model.wdl
     testParameterFiles:
          - /scripts/cnn_variant_wdl/jsons/cram2model.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: Funcotator
     subclass: WDL
     primaryDescriptorPath: /scripts/funcotator_wdl/funcotator.wdl
     testParameterFiles:
          - /scripts/funcotator_wdl/funcotator.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: GvsExtractCallset
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/GvsExtractCallset.wdl
     filters:
         branches:
             - master
             - ah_var_store
             - kl_gvs_walker_for_pgen
   - name: MitochondriaPipeline
     subclass: WDL
     primaryDescriptorPath: /scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl
     testParameterFiles:
          -  /scripts/mitochondria_m2_wdl/ExampleInputsMitochondriaPipeline.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: mutect2
     subclass: WDL
     primaryDescriptorPath: /scripts/mutect2_wdl/mutect2.wdl
     testParameterFiles:
          - /scripts/m2_cromwell_tests/mutect2.inputs.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: mutect2_pon
     subclass: WDL
     primaryDescriptorPath: /scripts/mutect2_wdl/mutect2_pon.wdl
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: run_happy
     subclass: WDL
     primaryDescriptorPath: /scripts/cnn_variant_wdl/run_happy.wdl
     testParameterFiles:
          - /scripts/cnn_variant_wdl/jsons/run_happy.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: pathseq_pipeline
     subclass: WDL
     primaryDescriptorPath: /scripts/pathseq/wdl/pathseq_pipeline.wdl
     testParameterFiles:
          - /scripts/pathseq/wdl/pathseq_pipeline_template.json
     filters:
         branches:
             - master
         tags:
             - /.*/
   - name: GvsExtractCallsetPgen
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/GvsExtractCallsetPgen.wdl
     filters:
         branches:
             - kl_gvs_walker_for_pgen
   - name: GvsExtractCallsetPgenMerged
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/GvsExtractCallsetPgenMerged.wdl
     filters:
         branches:
             - kl_gvs_walker_for_pgen
   - name: MergePgen
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/MergePgen.wdl
     filters:
         branches:
             - kl_gvs_walker_for_pgen
   - name: MergePgenHierarchicalWdl
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/MergePgenHierarchical.wdl
     filters:
         branches:
             - kl_gvs_walker_for_pgen
   - name: ComparePgenAndVcfScatter
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/pgen_validation/ComparePgenAndVcfScatter.wdl
     filters:
         branches:
             - kl_gvs_walker_for_pgen