version: 1.2
workflows:
   - name: ImportGenomes
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/ImportGenomes.wdl
     testParameterFiles:
       - /scripts/variantstore/wdl/ImportGenomes.example.inputs.json
     filters:
       branches:
         - master
         - ah_var_store
         - inline_schema