version: 1.2
workflows:
   - name: ImportGenomes
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/ImportGenomes.wdl
     testParameterFiles:
       - /scripts/variantstore/wdl/ImportGenomes.example.inputs.json
     filters:
       branches:
         - ah_var_store
   - name: ImportGenomes_LoadTable
     subclass: WDL
     primaryDescriptorPath: /scripts/variantstore/wdl/ImportGenomes_LoadTable.wdl
     testParameterFiles:
       - /scripts/variantstore/wdl/ImportGenomes_LoadTable.example.inputs.json
     filters:
       branches:
         - bq_15tb_limit
