# Use the specified base image
FROM hz-registry.nferx.com/ubuntu as builder

# Set the working directory in the container
WORKDIR /usr/src/app
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
# Install required packages and dependencies
RUN apt-get update && \
    apt-get install -y \
    openjdk-17-jdk \
    python3-pip \
    python3-venv \
    git \
    build-essential \
    libtool \
    zlib1g-dev \
    liblzma-dev \
    git-lfs && \
    rm -rf /var/lib/apt/lists/*

# Set up Python environment and install packages
RUN python3 -m venv venv && \
    . venv/bin/activate && \
    pip install --upgrade pip setuptools wheel && \
    pip install Flask pandas && \
    pip cache purge && \
    ln -s /usr/bin/python3 /usr/bin/python &&\
    git lfs install

# Copy the application files
COPY . gatk/

# Build the GATK jar file
RUN cd gatk && \
    ./gradlew localJar && \
    mv build/libs/gatk-package* /usr/src/app/gatk.jar && \
    cd .. && \
    rm -rf gatk/ && \
    rm -rf /root/.gradle && \
    apt-get remove -y git-lfs
