select location, sample_id,
       SPLIT(minimize(ref, SPLIT(alt,',')[OFFSET(0)]))[OFFSET(0)] as ref,
       SPLIT(minimize(ref, SPLIT(alt,',')[OFFSET(0)]))[OFFSET(1)] as allele,
       1 as allele_pos, call_GT, call_GQ,
       as_raw_mq,
       cast(SPLIT(as_raw_mq,'|')[OFFSET(1)] as int64) raw_mq,
       as_raw_mqranksum,
       SAFE_cast(SAFE_cast(SPLIT(as_raw_mqranksum,',')[SAFE_OFFSET(0)] as float64) * 10.0 as int64) as raw_mqranksum_x_10,
       as_qualapprox,
       qualapprox,
       cast(SPLIT(as_qualapprox,'|')[OFFSET(0)] as int64) as qual,
       as_raw_readposranksum,
       SAFE_cast(SAFE_cast(SPLIT(as_raw_readposranksum,',')[SAFE_OFFSET(0)] as float64) * 10.0 as int64) as raw_readposranksum_x_10,
       as_sb_table,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(0)],',')[OFFSET(0)] as int64) as sb_ref_plus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(0)],',')[OFFSET(1)] as int64) as sb_ref_minus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(1)],',')[OFFSET(0)] as int64) as sb_alt_plus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(1)],',')[OFFSET(1)] as int64) as sb_alt_minus,
       call_AD,
       cast(SPLIT(call_AD,',')[OFFSET(0)] as int64) as ref_ad,
       cast(SPLIT(call_AD,',')[OFFSET(1)] as int64) as ad
from position1

union all

select location, sample_id,
       SPLIT(minimize(ref, SPLIT(alt,',')[OFFSET(0)]))[OFFSET(0)] as ref,
       SPLIT(minimize(ref, SPLIT(alt,',')[OFFSET(0)]))[OFFSET(1)] as allele,
       1 as allele_pos, call_GT, call_GQ,
       as_raw_mq,
       cast(SPLIT(as_raw_mq,'|')[OFFSET(1)] as int64) raw_mq,
       as_raw_mqranksum,
       SAFE_cast(SAFE_cast(SPLIT(as_raw_mqranksum,',')[SAFE_OFFSET(0)] as float64) * 10.0 as int64) as raw_mqranksum_x_10,
       as_qualapprox,
       qualapprox,
       cast(SPLIT(as_qualapprox,'|')[OFFSET(0)] as int64) as qual,
       as_raw_readposranksum,
       SAFE_cast(SAFE_cast(SPLIT(as_raw_readposranksum,',')[SAFE_OFFSET(0)] as float64) * 10.0 as int64) as raw_readposranksum_x_10,
       as_sb_table,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(0)],',')[OFFSET(0)] as int64) as sb_ref_plus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(0)],',')[OFFSET(1)] as int64) as sb_ref_minus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(1)],',')[OFFSET(0)] as int64) as sb_alt_plus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(1)],',')[OFFSET(1)] as int64) as sb_alt_minus,
       call_AD,
       cast(SPLIT(call_AD,',')[OFFSET(0)] as int64) as ref_ad,
       cast(SPLIT(call_AD,',')[OFFSET(1)] as int64) as ad
from position2

union all

select location, sample_id,
       SPLIT(minimize(ref, SPLIT(alt,',')[OFFSET(1)]))[OFFSET(0)] as ref,
       SPLIT(minimize(ref, SPLIT(alt,',')[OFFSET(1)]))[OFFSET(1)] as allele,
       2 as allele_pos, call_GT, call_GQ,
       as_raw_mq,
       cast(SPLIT(as_raw_mq,'|')[OFFSET(2)] as int64) raw_mq,
       as_raw_mqranksum,
       SAFE_cast(SAFE_cast(SPLIT(as_raw_mqranksum,',')[SAFE_OFFSET(1)] as float64) * 10.0 as int64) as raw_mqranksum_x_10,
       as_qualapprox,
       qualapprox,
       cast(SPLIT(as_qualapprox,'|')[OFFSET(1)] as int64) as qual,
       as_raw_readposranksum,
       SAFE_cast(SAFE_cast(SPLIT(as_raw_readposranksum,',')[SAFE_OFFSET(1)] as float64) * 10.0 as int64) as raw_readposranksum_x_10,
       as_sb_table,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(0)],',')[OFFSET(0)] as int64) as sb_ref_plus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(0)],',')[OFFSET(1)] as int64) as sb_ref_minus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(2)],',')[OFFSET(0)] as int64) as sb_alt_plus,
       cast(SPLIT(SPLIT(as_sb_table,'|')[OFFSET(2)],',')[OFFSET(1)] as int64) as sb_alt_minus,
       call_AD,
       cast(SPLIT(call_AD,',')[OFFSET(0)] as int64) as ref_ad,
       cast(SPLIT(call_AD,',')[OFFSET(2)] as int64) as ad
from position2;
