package org.broadinstitute.hellbender.tools.sv.cluster;

import htsjdk.variant.variantcontext.Allele;
import org.broadinstitute.hellbender.tools.spark.sv.utils.GATKSVVCFConstants;
import org.broadinstitute.hellbender.tools.spark.sv.utils.GATKSVVCFConstants.ComplexVariantSubtype;
import org.broadinstitute.hellbender.tools.spark.sv.utils.GATKSVVCFConstants.StructuralVariantAnnotationType;
import org.broadinstitute.hellbender.tools.sv.SVCallRecord;
import org.broadinstitute.hellbender.tools.sv.SVTestUtils;
import org.broadinstitute.hellbender.utils.SimpleInterval;
import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class CrossSubtypeLinkageUnitTest {

    private static final CrossSubtypeLinkage<SVCallRecord> LINKAGE = new CrossSubtypeLinkage<>(SVTestUtils.hg38Dict);
    private static final List<Allele> CPX_ALLELES = List.of(Allele.REF_N, SVTestUtils.CPX_ALLELE);

    @DataProvider(name = "crossSubtypePairs")
    public Object[][] crossSubtypePairs() {
        return new Object[][]{
                {"dDUP_vs_dupINV_true",
                        new SVCallRecord("ddup", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 3500,
                                        GATKSVVCFConstants.SINK_END, 3510
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("dupinv", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINV,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6020, 7980)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3010, 3500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        true},
                {"dDUP_vs_INVdup_true",
                        new SVCallRecord("ddup", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 3000,
                                        GATKSVVCFConstants.SINK_END, 3010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("invdup", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.INVdup,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3490)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6010, 7990))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        true},
                {"dDUP_vs_dupINV_false_missing_sink_match",
                        new SVCallRecord("ddup", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 4100,
                                        GATKSVVCFConstants.SINK_END, 4110
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("dupinv", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINV,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6020, 7980)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3010, 3500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"dDUP_vs_INS_iDEL_true",
                        new SVCallRecord("ddup", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP,
                                List.of(new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000))),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9000,
                                        GATKSVVCFConstants.SINK_END, 9010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("insidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.INS_iDEL,
                                List.of(new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INS, new SimpleInterval("chr1", 6020, 7980))),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9010,
                                        GATKSVVCFConstants.SINK_END, 9020
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        true},
                {"dDUP_iDEL_vs_INS_iDEL_true",
                        new SVCallRecord("ddupidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8200, 8500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9000,
                                        GATKSVVCFConstants.SINK_END, 9010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("insidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.INS_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INS, new SimpleInterval("chr1", 6010, 7990)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8210, 8490))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9010,
                                        GATKSVVCFConstants.SINK_END, 9020
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        true},
                {"dDUP_iDEL_vs_INS_iDEL_false_inv_presence_mismatch",
                        new SVCallRecord("ddupidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3500)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8200, 8500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9000,
                                        GATKSVVCFConstants.SINK_END, 9010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("insidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.INS_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INS, new SimpleInterval("chr1", 6010, 7990)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8210, 8490))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9010,
                                        GATKSVVCFConstants.SINK_END, 9020
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"dupINV_vs_dupINVdup_false",
                        new SVCallRecord("dupinv", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINV,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1100, 1400)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1500, 1800))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("dupinvdup", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINVdup,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1110, 1410)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1850, 2150))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"INVdup_vs_delINVdup_false",
                        new SVCallRecord("invdup", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.INVdup,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1500, 1800)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1850, 2150))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("delinvdup", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINVdup,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1100, 1400)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1860, 2140))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"delINV_vs_delINVdel_false",
                        new SVCallRecord("delinv", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINV,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1100, 1400)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1500, 1800))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("delinvdel", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1110, 1410)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1850, 2150))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"INVdel_vs_delINVdel_false",
                        new SVCallRecord("invdel", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.INVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1500, 1800)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1850, 2150))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("delinvdel", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1110, 1410)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1860, 2140))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"dupINV_vs_delINVdel_false_non_inv_interval_mismatch",
                        new SVCallRecord("dupinv", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINV,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1100, 1400)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1500, 1800))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("delinvdel", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1110, 1410)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1860, 2140))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"dDUP_iDEL_vs_dupINVdel_true",
                        new SVCallRecord("ddupidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3500)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8200, 8500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9000,
                                        GATKSVVCFConstants.SINK_END, 9010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("dupinvdel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6010, 7990)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3010, 3490)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8210, 8490))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        true},
                {"dDUP_iDEL_vs_delINVdup_true",
                        new SVCallRecord("ddupidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3000, 3500)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8200, 8500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9000,
                                        GATKSVVCFConstants.SINK_END, 9010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("delinvdup", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINVdup,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8210, 8490)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3010, 3490)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6010, 7990))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        true},
                {"dDUP_iDEL_vs_dupINVdel_false_missing_inv",
                        new SVCallRecord("ddupidel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP_iDEL,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8200, 8500))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 9000,
                                        GATKSVVCFConstants.SINK_END, 9010
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("dupinvdel", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6010, 7990)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 3010, 3490)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 8210, 8490))
                                ),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"same_subtype_false",
                        new SVCallRecord("left", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP,
                                List.of(new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6000, 8000))),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 3500,
                                        GATKSVVCFConstants.SINK_END, 3510
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("right", "chr1", 1000, null,
                                "chr1", 1000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dDUP,
                                List.of(new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 6010, 7990))),
                                2000,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Map.of(
                                        GATKSVVCFConstants.SINK_CHROM, "chr1",
                                        GATKSVVCFConstants.SINK_POS, 3510,
                                        GATKSVVCFConstants.SINK_END, 3520
                                ),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
                {"no_supported_cross_subtype_rule_false",
                        new SVCallRecord("dupinvdup", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.dupINVdup,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1110, 1410)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DUP, new SimpleInterval("chr1", 1850, 2150))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        new SVCallRecord("delinvdel", "chr1", 1000, null,
                                "chr1", 2000, null,
                                StructuralVariantAnnotationType.CPX,
                                ComplexVariantSubtype.delINVdel,
                                List.of(
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1110, 1410)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.INV, new SimpleInterval("chr1", 1510, 1790)),
                                        new SVCallRecord.ComplexEventInterval(StructuralVariantAnnotationType.DEL, new SimpleInterval("chr1", 1860, 2140))
                                ),
                                1001,
                                Collections.emptyList(),
                                SVTestUtils.PESR_ONLY_ALGORITHM_LIST,
                                CPX_ALLELES,
                                Collections.emptyList(),
                                Collections.emptyMap(),
                                Collections.emptySet(),
                                null,
                                SVTestUtils.hg38Dict),
                        false},
        };
    }

    @Test(dataProvider = "crossSubtypePairs")
    public void testAreClusterableAcrossComplexSubtypes(final String name,
                                                        final SVCallRecord left,
                                                        final SVCallRecord right,
                                                        final boolean expected) {
        final CanonicalSVLinkage.CanonicalLinkageResult forward = LINKAGE.areClusterable(left, right);
        final CanonicalSVLinkage.CanonicalLinkageResult reverse = LINKAGE.areClusterable(right, left);

        Assert.assertEquals(forward.getResult(), expected, name);
        Assert.assertEquals(reverse.getResult(), expected, name + " reverse");

        if (expected) {
            Assert.assertNotNull(forward.getBreakpointDistance1(), name);
            Assert.assertNotNull(forward.getBreakpointDistance2(), name);
        }
    }
}