package org.broadinstitute.hellbender.tools.walkers.haplotypecaller.STR;

/**
 * Created by valentin on 12/4/16.
 */
enum STREvaluationClass {
    FALSE_POSITIVE, TRUE_NEGATIVE, FALSE_NEGATIVE, UNKNOWN_POSITIVE,
    UNKNOWN_NEGATIVE, TRUE_POSITIVE_HET, DISCORDANT_POSITIVE_ALLELE_HET, DISCORDANT_POSITIVE_HET_TO_HOM,
    DISCORDANT_POSITIVE_ALLELE_HET_TO_HOM, DISCORDANT_POSITIVE_HET_TO_COMPOSITE, DISCORDANT_POSITIVE_ALLELE_HET_TO_COMPOSITE,
    DISCORDANT_POSITIVE_HOM_TO_COMPOSITE, DISCORDANT_POSITIVE_COMPOSITIVE_TO_HOM, DISCORDANT_POSITIVE_COMPOSITE_TO_HET,
    TRUE_POSITIVE_COMPOSITE, DISCORDANT_POSITIVE_ALLELE_COMPOSITE_TO_HOM, DISCORDANT_POSITIVE_ALLELE_COMPOSITE,
    DISCORDANT_POSITIVE_ALLELE_HOM_TO_COMPOSITE, DISCORDANT_POSITIVE_ALLELE_HOM_TO_HET, DISCORDANT_POSITIVE_HOM_TO_HET,
    DISCORDANT_POSITIVE_ALLELE_HOM, TRUE_POSITIVE_HOM;
}
