STATE_DICT_NAME = 'model_state_dict'
ARTIFACT_LOG_PRIORS_NAME = 'artifact_log_priors'
ARTIFACT_SPECTRA_STATE_DICT_NAME = 'artifact_spectra_state_dict'
HYPERPARAMS_NAME = 'hyperparams'
NUM_READ_FEATURES_NAME = 'num_read_features'
NUM_INFO_FEATURES_NAME = 'num_info_features'
REF_SEQUENCE_LENGTH_NAME = 'ref_sequence_length'
HIDDEN_LAYERS_NAME = 'hidden_layers'
NUM_BASE_FEATURES_NAME = 'num_base_features'
NUM_REF_ALT_FEATURES_NAME = 'num_ref_alt_features'

SOURCES_NAME = 'sources'
SOURCE_NAME = 'source'

INPUT_NAME = 'input'
OUTPUT_NAME = 'output'
OUTPUT_DIR_NAME = 'output_dir'

READ_LAYERS_NAME = 'read_layers'
SELF_ATTENTION_HIDDEN_DIMENSION_NAME = 'self_attention_hidden_dimension'
NUM_SELF_ATTENTION_LAYERS_NAME = 'num_self_attention_layers'

LEARNING_METHOD_NAME = 'learning_method'

INFO_LAYERS_NAME = 'info_layers'
AGGREGATION_LAYERS_NAME = 'aggregation_layers'
CALIBRATION_LAYERS_NAME = 'calibration_layers'
REF_SEQ_LAYER_STRINGS_NAME = 'ref_seq_layer_strings'
DROPOUT_P_NAME = 'dropout_p'
LEARNING_RATE_NAME = 'learning_rate'
WEIGHT_DECAY_NAME = 'weight_decay'
BATCH_NORMALIZE_NAME = 'batch_normalize'
LEARN_ARTIFACT_SPECTRA_NAME = 'learn_artifact_spectra'

TRAINING_DATASETS_NAME = 'training_datasets'
TRAIN_TAR_NAME = 'train_tar'
EVALUATION_TAR_NAME = 'evaluation_tar'
TEST_DATASET_NAME = 'test_dataset'
NORMAL_ARTIFACT_DATASETS_NAME = 'normal_artifact_datasets'
REWEIGHTING_RANGE_NAME = 'reweighting_range'
BATCH_SIZE_NAME = 'batch_size'
CHUNK_SIZE_NAME = 'chunk_size'
NUM_EPOCHS_NAME = 'num_epochs'
NUM_CALIBRATION_EPOCHS_NAME = 'num_calibration_epochs'
INFERENCE_BATCH_SIZE_NAME = 'inference_batch_size'
NUM_WORKERS_NAME = 'num_workers'
NUM_SPECTRUM_ITERATIONS_NAME = 'num_spectrum_iterations'
SPECTRUM_LEARNING_RATE_NAME = 'spectrum_learning_rate'

DATASET_EDIT_TYPE_NAME = 'dataset_edit'

TENSORBOARD_DIR_NAME = 'tensorboard_dir'

INITIAL_LOG_VARIANT_PRIOR_NAME = 'initial_log_variant_prior'
INITIAL_LOG_ARTIFACT_PRIOR_NAME = 'initial_log_artifact_prior'
CONTIGS_TABLE_NAME = 'contigs_table'
GENOMIC_SPAN_NAME = 'genomic_span'
MAF_SEGMENTS_NAME = 'maf_segments'
NORMAL_MAF_SEGMENTS_NAME = 'normal_maf_segments'
GERMLINE_MODE_NAME = 'germline_mode'
NO_GERMLINE_MODE_NAME = 'no_germline_mode'
HET_BETA_NAME = 'het_beta'

BASE_MODEL_NAME = 'base_model'
M3_MODEL_NAME = 'permutect_model'
PRETRAINED_MODEL_NAME = 'pretrained_model'
