package org.broadinstitute.hellbender.tools.spark.linkedreads;

import org.testng.annotations.Test;

public class ComputeReadEntropySparkUnitTest {

    @Test
    public void testComputeEntropy() {
        System.out.println(ReadEntropyFilter.computeEntropy("TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"));
        System.out.println(ReadEntropyFilter.computeEntropy("TTTTTACTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"));
        System.out.println(ReadEntropyFilter.computeEntropy("ACTGCATATTCTCACTTATAAGTGGGAGCTAAATGATAAGAACTTATGAACACAAAGAAGGAAACATCAGACACTGGGGTCTAGTTGAGTGGGAAAGGTGGGAGGAGGGAGAGGAGCAGAAAAGATAATTATTGGGTACTGGGTTTAATTC"));
        System.out.println(ReadEntropyFilter.computeEntropy("ACTGCATATTCTCACTTATAAGTGGGAGCTAAATGATAAGAACTTATGAACACAAAGAAGGAAACATCAGACACTGGGGTCTAGTTTATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATAT"));
        System.out.println(ReadEntropyFilter.computeEntropy("ATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATA"));
        System.out.println(ReadEntropyFilter.computeEntropy("ATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCA"));
        System.out.println(ReadEntropyFilter.computeEntropy("ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATC"));
        System.out.println(ReadEntropyFilter.computeEntropy("ATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTA"));
        System.out.println(ReadEntropyFilter.computeEntropy("ACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACA"));
        System.out.println(ReadEntropyFilter.computeEntropy("ACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTG"));
        System.out.println(ReadEntropyFilter.computeEntropy("CACCCCCCCACCCCCCCGCTCCCCCCCCTCCCCCCCCCCACCCACCCCTCCCCCACTCACCTCCCCCCCCACTCACCCGCCCGTTCCCCCACTCACCCACCCACCACCCGCCCATCCATCCATCCATCCACCCAACCCACTCACCCCACCC"));
        System.out.println(ReadEntropyFilter.computeEntropy("CACACCTACACATCCACCCACCCACCCATCCATCCATCACCCATCTACCCACCCACTCACCTGCACGTTCACCCACTCATCCACCCAACACCCGCCCATCCATCCAACCATTCATCCATGCCTCCATCCATCCACCCATCCATCCATCTAC"));
        System.out.println(ReadEntropyFilter.computeEntropy("CACCCCACCCCCCACCCCCCCCCCCCGCTCCCCCCCCCCACCCCCCCCTACCCCCCCCCCCCCCCCCCCCCCTACCCACCCACCCACCCACTCATCCCTCCACCCACCCACCCAGCCACCCATCCACTCATCCATCCACCCAATGCCCACC"));
    }
}