package org.broadinstitute.hellbender.tools.spark.linkedreads;

import org.testng.annotations.Test;

public class ComputeReadEntropySparkUnitTest {

    @Test
    public void testComputeEntropy() {
        System.out.println(ComputeReadEntropySpark.computeEntropy("TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("TTTTTACTGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ACTGCATATTCTCACTTATAAGTGGGAGCTAAATGATAAGAACTTATGAACACAAAGAAGGAAACATCAGACACTGGGGTCTAGTTGAGTGGGAAAGGTGGGAGGAGGGAGAGGAGCAGAAAAGATAATTATTGGGTACTGGGTTTAATTC"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ACTGCATATTCTCACTTATAAGTGGGAGCTAAATGATAAGAACTTATGAACACAAAGAAGGAAACATCAGACACTGGGGTCTAGTTTATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATAT"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATATA"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCATCA"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATC"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTATCGTA"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACACTGACA"));
        System.out.println(ComputeReadEntropySpark.computeEntropy("ACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTGACTACTG"));
    }
}